Squashed 'libreoffice-core/' changes from 3ac458599f..a0612242a3
a0612242a3 LOK: fixed incorrect Logic point calculation for Map mode
ec9315aba1 LOK: Use frozen map instead of a chain of hundreds string comparisons
790e1d7966 LOK: Send view modes status change notifications
1fdfb51229 LOK: differentiate page kinds in sd::ViewShellBase::getEditMode
36a7ff080a annot: add {add,remove}Annotation that don't notify
d051319a8f annot: prepare SdrObject to represent an annotation
fa7fedd575 annot: improve PDF annotation export and clean-up PDFNote class
4168e37a45 vcl: document and simplify PDFAnnotationMarker
ddb454bb80 lok: sw: fix PageDown position when cursor is not visible
54d8c1b8f2 svx: adjust the values for impress/draw ruler to work with LOKit
dded9c034b tdf#161443 DOCX import, table style: handle para border in table cell paras
36e4c8287e annot: move TextAPI to svx and adapt the code
8331778d5c annot: use smart pointers in TextAPIEditSource and clean-up
fdb0593e1e tdf#161443 DOCX import, table style: fix para border leaking into cell border
179831344c more stale hyphenation data after skipping blanks
39fe35549d annot: make TextApi use SdrModel instead of SdDrawDocument
037196e635 annot: moved more of Annotation and dependencies into svx
3693180fd7 Resolves: tdf#161430 reindex the correct style if there are duplicate names
f5ffa35676 Avoid potential negative array index access to cached text.
db27cd2246 LOK: do not use deprecated .uno:BackColor
ec5c4b572b annot: move UndoAnnotation and deps. to svx, adapt svx Annotation
83b6adcd0d annot: added Annotation impl. to svx, moved some thing from sd
65fa3d18ce prep AutoFill menu in kit mode only
12c8d404f4 stale hyphenation data after skipping blanks
cd3a21a574 if we don't have local help then Help::GetHelpText will be empty
c2b5095d83 cool#9082 - lok: cleanup WakeUpThread before forking, then re-start.
21bc7cb8c9 tdf#144752: UNDO/REDO: make sure to select the replaced content
fbe6d3072d tdf#136294: trigger pending spellcheck in SwCursorShell::UpdateCursor
67295a5ce5 Revert "tdf#160706 speed up loading conditional formatting rule in XLS (II)"
fdb5e53af8 Bump version to 24.04.4.1
a17e087e26 lok: sw: do not add a table style on insert dialog
18d295cb58 Improvement to conditional formatting naming
c080c25985 tdf#160984 sw continuous endnotes: hide not functional UI in this mode
3939d516fd tdf#160984 sw continuous endnotes: fix the endnote continuation separator len
a96dd31ad4 Make sure that the big value doesn't readily overflow
71c8a9bc54 partial revert to restore existence of Expander wrappers
9fd2a69026 tdf#160589: compare the correct OutDev with PageWindows
0ed516d3a5 Consolidate on a single Updater::log overload
d422233304 Make sure updates dir exists when writing updating.log
6daf242d84 tdf#161292: Fix create-partial-info for newly added files
ecd946a063 Resolves: tdf#158789 operate on query array if no extra array or range given
ea5fdd799f Update git submodules
55ba5fccba Update git submodules
140b59d37f Update git submodules
f1338ba7de tdf#161318 sw clearing break: fix this at section end
44fda102b2 tdf#161288 Traditional Chinese minus character is U+8CA0(負), not U+5069(偩)
1aa0df8a21 Related: tdf#161301 strip single stray leading "[$]" garbage from formatCode
987c801c56 update credits
794347f99f Fix some macOS memory leaks due to overretaining Objective-C objects
44a2aedaf1 Related: tdf#160056 call FormulaCompiler::IsOpCodeJumpCommand just once
93eb455b7a Properly fix use of uninitialized value
80f3a0b928 cid#1598442 Dereference null return value
c9a79120a8 Simplify a bit
6e4f4c8bea Resolves: tdf#160371 Relax significant whitespace intersection pre-check
d319835d2c Related tdf#158914: fix memory leaks by calling (auto)release selectors
c20d571012 sc: warning C6011: Dereferencing NULL pointer
dfc1586d2b related tdf#158914 sc a11y: Release references when disposing sheet
02421faf21 sw: warning C6011: Dereferencing NULL pointer
acbf585bbe sfx2: warning C6011: Dereferencing NULL pointer
2d66c1ccb2 Revert "tdf#126095 sd notebookbar: don't force table/media toolbar"
8f51df6568 sc: check GetActiveViewShell()
485c661e14 update language-subtag-registry to 2024-05-16
1f40712d75 Resolves: tdf#160804 sc: ResizeMatrix: Use document grammar
544dfd9d85 tdf#160884: Apply scale to position of embedded images in Type 3 fonts
11074ab281 Resolves: tdf#151382 we want to save the FN_KEEP_ASPECT_RATIO state
27f97a11b9 Resolves: tdf#161133 read-only widget should have deactivated calendar
70fdbc4cd8 Resolves: tdf#157453 support FM_PROP_LINECOUNT for combobox dropdow rows
ab33c8f661 tdf#155651: Add support for "context-fill"
a05ee9324f sw: make testTdf131963 less strict
f5aac51ce2 tdf#160565 tdf#145735 qt: Avoid native window handles for Qt 6
d43562e03d ONLINE: Add Invert document background color command.
f552aa1276 tdf#161202: lowers shouldn't move forward because of lack of space
709b56249f tdf#161354: drop incorrect assertion
932a01d975 tdf#160958: merge hidden section's follows; move first-on-page section back
946ca1b3f7 ubsan: runtime error: reference binding to null pointer of type 'const SwFrame'
317ca78624 tdf#161318 sw clearing break: ignore wrap-through anchored objects
d0ee0c93d6 tdf#160984 sw continuous endnotes: DOCX: export of <w:endnotePr> pos == sectEnd
fd22acaf89 lok: document some guidelines on how to not end up with too many callbacks
dc3e624b52 change Structure label of Function Wizard dialog
c5a7ff366f cool#9174 - Enable .uno:ChangeBezier
928d0ffc25 create comment reply synchronously
812d5e98dc tdf#160984 sw continuous endnotes: DOCX: import <w:endnotePr> pos == sectEnd
a3f4d31783 add AutoFill menu items - LOK_CALLBACK_CONTEXT_MENU
5357f69c27 Bump version to 24.04.3.2
338b3ba86c [cp] On Windows only build selected helppacks (en-US, fr, de, it, es)
f29be6b680 Resolves: tdf#161057 draw/impress auto font color not updated on theme change
ba0f1432e2 tdf#160984 sw continuous endnotes: fix crash on loading forum-mso-en-7731.docx
69bbd6378e tdf#160984 sw continuous endnotes: fix the endnote separator length
461447cfdc tdf#160984 sw continuous endnotes: fix the endnote separator position
724250d63d tdf#161222: LOK: do not fine-tune text scaling for tile rendering
2802ba82d2 Fix a memory leak
6e322952a5 WakeupThread - re-factor to have a single shared wakeup thread.
3009eebbad sc: don't overwrite Special Positioning on MakeEditView
df2c39e978 tdf#161137 sw: AutoText or Paste should copy paragraph indents for lists
dbc5e22e4e tdf#160984 sw continuous endnotes: fix the endnote container's top margin
10b1f03728 tdf#160984 sw continuous endnotes: enable DOCX import
11eaf50179 lok: sc: fix print mode document back color
991341f9f6 Related: tdf#145972 sw images: fix rounding error in relative size calculation
3d071fcde4 split a piece of code out as a standalone GetOrCreateAnnotationWindow
34049fd79a tdf#161137 sw: fix AutoText or Paste overriding paragraph indents
18ca62ab83 Related: tdf#160725 - Add horizontal binary search mode for SortedCache
0f9a36e514 tdf#160725 - Fix XLOOKUP has different result for approximate
31b6e2c056 Bump version to 24.04.3.1
af38e96cad tdf#161172: Also record history for !bChangeOfListStyleAtParagraph
9225833331 fix build break wrt ‘Wait’ is not a member of ‘PointerStyle’
10ef0f03bb sw: show "wait" pointer while accessibility check is running
bb605f31f9 sc: LOK: invalidate sheet geometry on row height changes
3f90d8ac41 remove stray lines
2872e5dc20 writerfilter: avoid infinit loop when resolving embeddings on docx
0500d7cf47 writerfilter: fix parsing of invalid STYLEREF field
421ef056cf lok: translate formula bar functions to each locale
41130a39ad cool#9019: draw/impress: disable the Grid for now
66de531260 lok: join Webdav Ticker thread.
84ede4db04 lok: joinThreads - take down configmgr's write-thread.
5e6d7927e2 sw: add update button to a11y check sidebar when using LOKit
628f56a180 lok: stop amazing waste of repeated font sizes in each font element.
457f24c004 lok: stop amazing waste of pretty-printed JSON sent over the API.
f12e69cc4c tdf#161019 tdf#159846 spreadsheet border rendering
c2308ee58a tdf#160952 sw: ignore top margin only at page top, not in fly
39b9041a1e tdf#161035: The previous bookmarks can legitimately be not processed
97863cd0d4 Fix UBSan failure (part 2)
c244511404 Fix UBSan failure
274a004c6b sw: check GetUserCall
528f74855b tdf#153306 prevent subpixel shifting of X coordinate
8b6112e345 tdf#160906 use SfxPoolItemHolder
1eac6c0c02 tdf#161073 handle is supposed to be freed automatically on failure
14e89d9f3f Resolves: tdf#160985 Max integer representation for rtl_math_StringFormat_G
91ef48ca9d tdf#160690 set an opaque alpha mask for non-transparent frames
1aa90b5a2d tdf#160836 sw: fix narrow selection area of cell border
9a81bdda90 tdf#160836 sw: resize rows at images cropped by row height
66da0b7dee Update language-subtag-registry to 2024-03-07
11614498c1 tdf#160767 skip fix for tdf#155266 when the event hasn't changed
6f33df3f24 libxml2: upgrade to 2.12.7
aec722dcc6 tdf#160842 sw: select cell content instead of cropped part of image
8e2887a2aa tdf#44773 sw: allow resizing table rows, if cursor outside the table
478fb1937b sw: Navigator: don't show virtual drawing objects
5fe8b71b10 gbuild: don't create empty services.rdb on "make postprocess"
a5af864295 framework: MenuBarManager: fix WNT crash if queryDispatch() throws
e1d74c4a29 return early on empty ORelationTableConnectionData*
7660afce30 fix linker error for PCH build
c8621ea412 update credits
314dac8e58 tdf#160153 Restore Storage config item
5292f922ed tdf#160855 fix crash due to Skia's internal maximum pixel limit
18102e3d7f cool#8570 single-element cache in MsLangId::getScriptType
8d979fae0c lok: dump more SfxViewShell state, and LOK notifier state on Windows.
63ba90e6ae desktop: fix warning C4100: 'pThis': unreferenced formal parameter
5c81267c2e Revert "LOK: Allow image upload from WOPI-like host with self-signed cert"
135e86e7e3 tdf#160984 sw continuous endnotes, DOC import: enable this unconditionally
896b046fc3 cool#8570 try to reduce CPU spent in MsLangId::getScriptType
9f26e04c8f svx: move lok's NotifyKit in the ruler to the SvxRuler super-class
2a040bfe3e Added parent / child relationship to comments.
19ac02dbae always restore existing interaction handler after save
a8216967eb tdf#161083 sw continuous endnotes: fix layout with a section at doc end
ad3586d6c6 tdf#160984 sw continuous endnotes: switch to a section-based layout
564b16720e make AutoFill work for Copy cells and Fill series
07c93a65d2 tdf#160952 sw: ignore top margin only at page top, not e.g. table top
348d36dc80 add explicit png build dependency to xpdfimport
a017e4637a tdf#156484 svx,sw: fix visibility of shapes in header/footer
44e79f0224 lok: get faster ModifiedStatus from the core.
11b936629d Add new LOK CALLBACK for vertical ruler
48ee8fb965 tdf#160984 sw continuous endnotes: fix CppunitTest_sw_layoutwriter3
a8785af77c tdf#160402 writerfilter: extend StyleMap with all Word styles
773fe1fe92 tdf#69192: add StartingSlide to SID_PRESENTATION and cmdline show=
b6f42a6006 tdf#160984 sw continuous endnotes: fix testContinuousEndnotesMoveBackwards
ec1c8270dd tdf#160402 writerfilter,sw: STYLEREF field can refer to character style
c6c1c7afc1 sw: avoid unwanted row height changes
90bd45d7a9 lok: add SAL_DISABLE_FSYNC environment to disable fsync.
7b61926fd6 lok: dumpState should truncate very long JSON messages.
24876e5611 lok: Don't dump empty aria properties in every JSON element.
3f15ad602d drop requirement for rtl_random_getBytes to have "Pool" arg
e747e6df64 tdf#160984 sw continuous endnotes: add a way to find the endnote section start
f6f5038be2 tdf#160402 filter,writerfilter: import locale-dependent STYLEREF names
863720dfc0 tdf#40142 sw: only check level for table of contents
f2f4ceb79a tdf#159375: remove initialization on Tools>Options
726b133fd8 sc: undo: unify height adjust logic in undo with regular logic
a578321434 Fix row deletion bug.
aa83638390 Fix column deletion bug.

git-subtree-dir: libreoffice-core
git-subtree-split: a0612242a395e1be1fe8383537bc5a82d6b882ac